apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: clone-deployment
  labels:
    autoscale: hpa
spec:
  selector:
    matchLabels:
      app: clone
  replicas: 1
  template:
    metadata:
      labels:
        app: clone
    spec:
      containers:
      - name: nginx
        image: nginx:1.18.0
        resources:
          requests:
            # memory: "100Mi"
            cpu: "500m"
          limits:
            # memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
