apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    autoscale: hpa
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1 # Update the version of nginx from 1.14.2 to 1.16.1
        resources:
          requests:
            # memory: "100Mi"
            cpu: "500m"
          limits:
            # memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
