apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  namespace: default
  name: python-custom-autoscaler
spec:
  template:
    spec:
      containers:
      - name: python-custom-autoscaler
        image: 192.168.10.197:5000/python-custom-autoscaler7:latest
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  config: 
    - name: interval
      value: "10000"
    - name: downscaleStabilization
      value: "60"
    - name: minReplicas
      value: "1"
    - name: maxReplicas
      value: "5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: python-custom-autoscaler
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers", "replicationcontrollers/scale"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["pods", "deployments", "deployments/scale", "replicasets", "replicasets/scale", "statefulsets", "statefulsets/scale"]
  verbs: ["*"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

