apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: python-custom-autoscaler
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers", "replicationcontrollers/scale"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["pods", "deployments", "deployments/scale", "replicasets", "replicasets/scale", "statefulsets", "statefulsets/scale"]
  verbs: ["*"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]